/**
 * Pre-made blocklists for Twitter Bio Filter
 */
const PREMADE_LISTS = {
    nsfw: [
        "nsfw",
        "throne.com",
        "onflyfans",
        "onlyfans",
        "kinky",
        "godess",
        "findom",
        "of.com",
        "🔞",
        "nude",
        "fetish",
        "subscribe to my of",
        "subscribe to my onlyfans",
        "lewd",
        "milf",
        "tease",
        "18+",
        "uncensored",
        "free of",
        "free onlyfans",
        "top 0.",
        "top .",
        "top 1%",
        "vip",
        "sexting",
        "link in bio",
        "link below bio",
        "adult content",
        "sub to my of",
        "sub to my onlyfans",
        "dick rate",
        "rate your",
        "findom",
        "sugar baby",
        "fetish",
        "spoil me",
        "wishlist",
        "naughty",
        "b/g",
        "g/g",
        "tits",
        "boobs",
        "squirt",
        "cumshot",
        "free trial",
        "trial link",
        "allmylinks",
        "no paywall",
        "curvy",
        // "💦",
        // "🍆",
        // "🍑",
        // "🦋",
        "beautiful girls",
        "back shots",
        "blowjob",
        "sexy",
        "click link to see more",
        "% on",
        "0.01%",
        "0.1%",
        "f1ndom",
        "more of me",
        "link.me",
        "5'",
        "free o f",
        "⬅",
        "➡",
        "⬆",
        "⬇",
        "↗",
        "↘",
        "↙",
        "↖",
        "↓",
        "↑",
        "↗",
        "↘",
        "↙",
        // "👇🏻", "👇🏼", "👇🏽", "👇🏾", "👇🏿", "👇",
        // "f👉🏻", "f👉🏼", "f👉🏽", "f👉🏾", "f👉🏿", "f👉",
        // "f 👉🏻", "f 👉🏼", "f 👉🏽", "f 👉🏾", "f 👉🏿", "f 👉",
        // "here👉🏻", "here👉🏼", "here👉🏽", "here👉🏾", "here👉🏿", "here👉",
        // "here 👉🏻", "here 👉🏼", "here 👉🏽", "here 👉🏾", "here 👉🏿", "here 👉",
        // "💕",
        // "😈",
        "it's free",
        "ll messages here",
        "free ⬇",
        "milkers",
        "chaterbate",
        "adult content",
        // "👅",
        // "💋",
        "i have one",
        "internet gf",
        "fanplacefinder",
        "tapforallmylinks",
        "gamersupps.gg",
        "hooters",
        "explicit",
        // "🌶",
        "i only respond",
        "respond here",
        "my of",
        "my o f",
        "more of me",
        "beacons",
        "hoo.be",
        "link below for more",
        "Link below bio",
        "premium",
        "snapchat",
        "Adults only",

    ],
    crypto: [
        "crypto",
        "nft",
        "blockchain",
        "wallet",
        "hodl",
        "coin",
        "ethereum",
        "cardano",
        "doge",
        "dogecoin",
        "shiba",
        "web3",
        "token",
        "to the moon",
        "x gains",
        "metamask",
        "meta mask",
        "funds retrieval",
        "liquidity provider",
        "liquidity pool",
        "liquidity mining",
        "seed phrase",
        "apes",
        "web3",
        "web 3",
        "web-3",
        "web3.0",
        "web 3.0",
        "web-3.0",
        "hosting giveaways"
    ],
    MAGA: [
        "maga",
        "america first",
        "AmericaFirst",
        "America Only",
        "AmericaOnly",
        "maha",
        "trump supporter",
        "pro 2a",
        "anti-woke",
        "anti woke",
        "AntiWoke",
        "fuck pronouns",
        "not a democracy",
        "trump 2024",
        "trump 2028",
        'vance 2028',
        "trump won 2020",
        "TrumpWon",
        "election fraud",
        "truth social",
        "unvaxxed",
        "un-vaxxed",
        "rumble",
        "americaproject.com",
        "Anti-Sheep",
        "AntiSheep",
        "Anti Sheep",
        "Charlie Kirk",
        "@FLVoiceNews",
        "globalism",
        "anti-Americanism",
        "@ACTforAmerica",
        "James Woods",
        "Wokeness",
        "Woke mind virus",
        "Newsmax",
        "Timcast",
        "@TuckerCarlson",
        "@RedState",
        "TheDebraLea",
        "45-47",
        "America is Back",
        "fake news"
    ],
    Racist: [
        "nationalist",
        "alt-right",
        "1488",
        "race war",
        "anti-semite",
        "14 words",
        "race realist",
        "groyper",
        "heritage not hate",
        "europe is for europeans",
        "europe awake",
        "redpilled",
        "christian nationalist",
        "blood and soil",
        "trad-",
        "tradcath",
        "european heritage",
        "white lives matter",
        "nigger",
        "niggers",
        "western values",
        "christ is king",
        "reimmigration",
        "re-immigration",
        "national socialist",
        "white race",
        "anti jew",
        "anti black",
        "anti-jew",
        "anti-black",
        "reform the uk",
        "reform uk",
        "hitlerist",
        "th generation american",
        "percent white",
        '% white',
        "pro white",
        "pro-white",
        "howling",
        "noticer",
        "america only",
        "christan west",
        // "卐",
        // "⚡⚡",
        // "ᛋᛋ",
        "RadioGenoa"
    ],
    FarLeft: [
        "communist",
        "marxist",
        "m-l",
        "maoist",
        "leninist",
        "tankie",
        "read theory",
        "impearialist",
        "ancom",
        "anarchist",
        "☭",
        "stalinist",
        "seize the means",
        "comrade",
        "agitprop",
        "means of production",
        "proletarian",
        "working class",
        "working-class",
        "workingclass",
        "leftist",
        "anti-capitalist",
        "anti capitalist",

    ]
};
